config/routes.rb
#-  -*- encoding : utf-8 -*- 
#- This Source Code Form is subject to the terms of the Mozilla Public
#- License, v. 2.0. If a copy of the MPL was not distributed with this
#- file, You can obtain one at http://mozilla.org/MPL/2.0/.

Sms::Engine.routes.draw do
  resources(:message_templates, :only => [:index, :new, :create, :edit, :update, :destroy])
end

app/models/sms/message.rb
#-  -*- encoding : utf-8 -*-
#- This Source Code Form is subject to the terms of the Mozilla Public
#- License, v. 2.0. If a copy of the MPL was not distributed with this
#- file, You can obtain one at http://mozilla.org/MPL/2.0/.

module Sms
  class Message < ActiveRecord::Base
    # attributes
    attr_accessible(:subscriber_id, :status, :phone_number, :body, :sid, :created_at)

    STATUSES = [:unknown, :received, :sending, :sent, :failed, :read]
    enum_attr(:status, STATUSES, :init => :unknown, :nil => false)

    # validations
    validates(:phone_number,
      :presence => true,
      :length => {:in => 10..12},
      :format => /^\d*$/)
    validates(:body,
      :length => {:maximum => 160})

    # associations
    belongs_to(:subscriber)
    belongs_to(:parent,
      :class_name => "Message")
    has_many(:children,
      :class_name => "Message",
      :foreign_key => :parent_id,
      :dependent => :destroy)

    # instance methods

    #
    def receive_reply(body, sid, created_at = nil)
      children.create(
        :subscriber_id => subscriber_id,
        :phone_number => phone_number,
        :body => body,
        :status => :received,
        :sid => sid,
        :created_at => created_at
      )
    end

    #
    def send_reply(body)
      children.create(
        :subscriber_id => subscriber_id,
        :phone_number => phone_number,
        :body => body,
        :status => :sent
      )
    end

    #
    def save_status(status, sid)
      self.status = status
      self.sid = sid
      save!
    end

    # class methods
    #
    def self.sent
      where{status == :sent.to_s}
    end

    #
    def self.received
      where{status == :received.to_s}
    end

    #
    def self.read
      where{status == :read.to_s}
    end

    #
    def self.received_or_read
      where{status >> [:received.to_s, :read.to_s]}
    end

    #
    def self.first_by_sid(value)
      where{sid == value.to_s}.first
    end

    #
    def self.send_message(phone_number, body)
      create!(
        :phone_number => phone_number,
        :body => body,
        :status => :sending
      )
    end

    #
    def self.receive_message(phone_number, body, sid, created_at = nil)
      create!(
        :phone_number => phone_number,
        :body => body,
        :status => :received,
        :sid => sid,
        :created_at => created_at
      )
    end

    def self.to_csv
      CSV.generate do |csv|
        csv << column_names
        all.each do |message|
          csv << message.attributes.values_at(*column_names)
        end
      end
    end

  end
end

app/models/sms/message_template.rb
#-  -*- encoding : utf-8 -*-
#- This Source Code Form is subject to the terms of the Mozilla Public
#- License, v. 2.0. If a copy of the MPL was not distributed with this
#- file, You can obtain one at http://mozilla.org/MPL/2.0/.

module Sms
  class MessageTemplate < ActiveRecord::Base
    # attributes
    attr_accessible(:system, :name, :desc, :body)

    # validations
    validates(:name,
      :allow_nil => true,
      :length => {:in => 2..64},
      :format => /^[\w_]*$/)
    validates(:desc,
      :presence => true,
      :length => {:in => 2..64},
      :format => /^[\w -]*$/)
    validates(:body,
      :presence => true,
      :length => {:maximum => 200})

    # class methods
    #
    def self.user
      where{system == false}
    end

    #
    def self.system
      where{system == true}
    end

    #
    def self.get_by_name(value)
      where{name == value.to_s}.first || raise("#{value} not_found")
    end

    def self.to_csv
      CSV.generate do |csv|
        csv << column_names
        all.each do |template|
          csv << template.attributes.values_at(*column_names)
        end
      end
    end
  end
end

app/models/sms/subscriber.rb
#-  -*- encoding : utf-8 -*-
#- This Source Code Form is subject to the terms of the Mozilla Public
#- License, v. 2.0. If a copy of the MPL was not distributed with this
#- file, You can obtain one at http://mozilla.org/MPL/2.0/.

module Sms
  class Subscriber < ActiveRecord::Base
    # attributes
    attr_accessible(:active, :phone_number)

    # validations
    validates(:active,
      :inclusion => {:in => [true, false]})
    validates(:phone_number,
      :uniqueness => true,
      :presence => true,
      :length => {:in => 10..12},
      :format => /^\d*$/)

    # associations
    has_many(:messages,
      :dependent => :destroy)

    # instance methods
    #
    def activate
      self.active = false
      save!
    end

    #
    def deactivate
      self.active = true
      save!
    end

    #
    def receive_message(body, sid, created_at = nil)
      messages.create!(
        :phone_number => phone_number,
        :body => body,
        :status => :received,
        :sid => sid,
        :created_at => created_at
      )
    end

    #
    def send_message_using_template(name, params = {})
      message_template = MessageTemplate.get_by_name(name)
      messages.create!(
        :phone_number => phone_number,
        :body => message_template.body % params,
        :status => :sending
      )
    end

    #
    def send_message(body)
      messages.create!(
        :phone_number => phone_number,
        :body => body,
        :status => :sending
      )
    end

    # class methods
    def self.active
      where{active == true}
    end

    #
    def self.first_by_phone_number(value)
      where{phone_number == value.to_s}.first
    end

    #
    def self.create_for(phone_number)
      create!(:phone_number => phone_number)
    end
  end
end

app/controllers/sms/base_controller.rb
#-  -*- encoding : utf-8 -*- 
#- This Source Code Form is subject to the terms of the Mozilla Public
#- License, v. 2.0. If a copy of the MPL was not distributed with this
#- file, You can obtain one at http://mozilla.org/MPL/2.0/.

module Sms
  class BaseController < ::ActionController::Base
  end
end

app/controllers/sms/message_templates_controller.rb
#-  -*- encoding : utf-8 -*- 
#- This Source Code Form is subject to the terms of the Mozilla Public
#- License, v. 2.0. If a copy of the MPL was not distributed with this
#- file, You can obtain one at http://mozilla.org/MPL/2.0/.

module Sms
  class MessageTemplatesController < BaseController
    include ::Authentication::AuthenticatedController
    respond_to(:html)
    layout("layouts/private/sms")

    before_filter(:only => :index) do
      page_param(:message_templates, 20)
      sort_param(:message_templates, :name, :asc)
    end

    #
    def index
      @message_templates = MessageTemplate
        .sorted_by(@sort_attribute, @sort_order)
        .paginate(:page => @page, :per_page => @per_page)
      # respond_with(@message_templates)
      respond_to do |format|
        format.html { @message_templates }
        format.csv  { send_data MessageTemplate.to_csv }
      end
    end

    #
    def new
      @message_template = MessageTemplate.new
      respond_with(@message_template)
    end

    #
    def create
      begin
        MessageTemplate.transaction do
          message_template = params[:message_template]
          @message_template = MessageTemplate.create!(message_template)
          flash[:notice] = t(:created)
          respond_with(@message_template, :location => message_templates_path)
        end

      rescue ActiveRecord::RecordInvalid => error
        @message_template = error.record
        respond_with(@message_template) do |format|
          format.html { render(:new) }
        end
      end
    end

    #
    def edit
      @message_template = MessageTemplate.find(params[:id])
      respond_with(@message_template)
    end

    #
    def update
      begin
        MessageTemplate.transaction do
          message_template = params[:message_template]
          @message_template = MessageTemplate.find(params[:id])
          @message_template.attributes = message_template
          @message_template.save!
          flash[:notice] = t(:updated)
          respond_with(@message_template, :location => message_templates_path)
        end

      rescue ActiveRecord::RecordInvalid => error
        @message_template = error.record
        respond_with(@message_template) do |format|
          format.html { render(:edit) }
        end
      end
    end

    #
    def destroy
      MessageTemplate.transaction do
        @message_template = MessageTemplate.find(params[:id])
        @message_template.destroy
        flash[:notice] = t(:destroyed)
        respond_with(@message_template, :location => message_templates_path)
      end
    end

  private
    #
    def t(key)
      I18n.t(key, :scope => [:sms, :message_templates])
    end
  end
end

app/views/sms/message_templates/_form.html.haml
//- This Source Code Form is subject to the terms of the Mozilla Public
//- License, v. 2.0. If a copy of the MPL was not distributed with this
//- file, You can obtain one at http://mozilla.org/MPL/2.0/.

-#- This Source Code Form is subject to the terms of the Mozilla Public
-#- License, v. 2.0. If a copy of the MPL was not distributed with this
-#- file, You can obtain one at http://mozilla.org/MPL/2.0/.

= render({:partial => "shared/errors", :object => @message_template})
= form_for([@message_template]) do |mt|
  = hidden_field_tag(:page, @page)
  %fieldset
    %legend= t(".legend")
    %ol
      %li
        = mt.label(:desc)
        = mt.text_field(:desc)
      %li
        = mt.label(:body)
        = mt.text_area(:body, {:size => "41x3", :maxlength => Sms::MESSAGE_TEMPLATE_BODY_MAX})
      %li
        .label= t(".character_count")
        %span#message_template_body_count
  %fieldset
    = link_to(t(".cancel"), message_templates_path, :class => "button")
    = mt.submit(t(".commit"), :data => {:disable_with => t(".commit_disable")})

:javascript
  function updateCount() {
    count = $('#message_template_body').val().length;
    countElement = $('#message_template_body_count');
    countElement.html(count);
    countElement.toggleClass('warning', count > #{Sms::MESSAGE_BODY_MAX});
  }

  $(function() {
    updateCount();
    $('#message_template_body').keyup(updateCount);
  });

app/views/sms/message_templates/_row.html.haml
//- This Source Code Form is subject to the terms of the Mozilla Public
//- License, v. 2.0. If a copy of the MPL was not distributed with this
//- file, You can obtain one at http://mozilla.org/MPL/2.0/.

-#- This Source Code Form is subject to the terms of the Mozilla Public
-#- License, v. 2.0. If a copy of the MPL was not distributed with this
-#- file, You can obtain one at http://mozilla.org/MPL/2.0/.

= content_tag_for(:tr, message_template, :class => "item") do
  %td= message_template.desc

  %td= truncate(message_template.body, :length => 40)

  %td
    - if !message_template.updated_at.nil?
      = l(message_template.updated_at)

  %td
    = link_to( |
        t(".edit_link"), |
        edit_message_template_path(message_template), |
        :class => "button")

    - if not message_template.system
      = link_to( |
          t(".destroy_link"), |
          message_template_path(message_template), |
          {:method => :delete, :data => {:confirm => t(".destroy_confirm"), :disable_with => t(".destroy_disable")}, :class => "button"})

app/views/sms/message_templates/_table.html.haml
//- This Source Code Form is subject to the terms of the Mozilla Public
//- License, v. 2.0. If a copy of the MPL was not distributed with this
//- file, You can obtain one at http://mozilla.org/MPL/2.0/.

-#- This Source Code Form is subject to the terms of the Mozilla Public
-#- License, v. 2.0. If a copy of the MPL was not distributed with this
-#- file, You can obtain one at http://mozilla.org/MPL/2.0/.

%table
  %tr
    = sorted_table_header_tag(:desc) do
      = t(".desc")

    = sorted_table_header_tag(:body) do
      = t(".body")

    = sorted_table_header_tag(:updated_at) do
      = t(".updated_at")

    = table_header_tag(t(".actions"))

  = render(:collection => @message_templates, :partial => "row", :as => :message_template)

app/views/sms/message_templates/edit.html.haml
//- This Source Code Form is subject to the terms of the Mozilla Public
//- License, v. 2.0. If a copy of the MPL was not distributed with this
//- file, You can obtain one at http://mozilla.org/MPL/2.0/.

-#- This Source Code Form is subject to the terms of the Mozilla Public
-#- License, v. 2.0. If a copy of the MPL was not distributed with this
-#- file, You can obtain one at http://mozilla.org/MPL/2.0/.

= render("form")

%fieldset
  %legend= t(".legend")
  %ol
    %li
      %span.label= t(".created_at")
      - if !@message_template.created_at.nil?
        = l(@message_template.created_at)
    %li
      %span.label= t(".updated_at")
      - if !@message_template.updated_at.nil?
        = l(@message_template.updated_at)

app/views/sms/message_templates/index.html.haml
//- This Source Code Form is subject to the terms of the Mozilla Public
//- License, v. 2.0. If a copy of the MPL was not distributed with this
//- file, You can obtain one at http://mozilla.org/MPL/2.0/.

-#- This Source Code Form is subject to the terms of the Mozilla Public
-#- License, v. 2.0. If a copy of the MPL was not distributed with this
-#- file, You can obtain one at http://mozilla.org/MPL/2.0/.

- content_for(:actions) do
  = link_to(t(".add_link"), new_message_template_path, :class => "button")
  = link_to("Download CSV", {:action => "index", :format => "csv"},:id => "download_csv", :class => "button" )

- if @message_templates.empty?
  = t(".no_message_templates")
- else
  = render("table")
  - content_for(:footer) do
    = will_paginate(@message_templates)

app/views/sms/message_templates/new.html.haml
//- This Source Code Form is subject to the terms of the Mozilla Public
//- License, v. 2.0. If a copy of the MPL was not distributed with this
//- file, You can obtain one at http://mozilla.org/MPL/2.0/.

-#- This Source Code Form is subject to the terms of the Mozilla Public
-#- License, v. 2.0. If a copy of the MPL was not distributed with this
-#- file, You can obtain one at http://mozilla.org/MPL/2.0/.

= render("form")